version: '3'
services:
  streamlit:
    build: ./
    ports:
      - '8501:8501'
    volumes:
      - './ebs/scrapper-data/Data-Tokopedia:/app/Data-Tokopedia:rw'
      - './ebs/scrapper-data/Data-Shopee:/app/Data-Shopee:rw'