version: '3'
services:
  streamlit:
    build:
      dockerfile: ./Dockerfile
    ports:
      - '8051:8051'
    volumes:
      - './ebs/scrapper-data/Data-Tokopedia:/app/Data-Tokopedia:rw'
      - './ebs/scrapper-data/Data-Shopee:/app/Data-Shopee:rw'